repos:
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django
