version: '3.5'
services:
  argus:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
      init:
        condition: service_completed_successfully
    environment:
      - TIME_ZONE=Europe/Amsterdam
      - DATABASE_URL=postgresql://argus:argus@postgres/argus
      - ARGUS_DISABLE_REDIS=True
      - POSTGRES_USER=argus
      - POSTGRES_PASSWORD=argus
      - POSTGRES_DB=argus
    restart: unless-stopped

  init:
    build: .
    depends_on:
      - postgres
    command: "/argus/initialize-db.sh"
    environment:
      - TIME_ZONE=Europe/Amsterdam
      - DATABASE_URL=postgresql://argus:argus@postgres/argus
      - ARGUS_DISABLE_REDIS=True
      - PGHOST=postgres
      - PGUSER=argus
      - PGPASSWORD=argus
      - PGDATABASE=argus

  postgres:
    image: "postgres:12"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=argus
      - POSTGRES_PASSWORD=argus
      - POSTGRES_DB=argus
