# Generated by Django 5.0.4 on 2024-07-05 10:31

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        TrigramExtension(),
    ]
