# Generated by Django 5.0.4 on 2024-07-05 08:35

from django.db import migrations

ARGUS_APP = "argus_incident"


class Migration(migrations.Migration):

    dependencies = [
        ("geant_argus", "0001_trigram_extension"),
        (ARGUS_APP, "0008_incident_metadata"),
    ]

    operations = [
        migrations.RunSQL(
            (
                f'CREATE INDEX "metadata_description_gin_idx" ON "{ARGUS_APP}_incident"'
                " USING gin ((\"metadata\" ->> 'description') gin_trgm_ops)"
            ),
            reverse_sql='DROP INDEX "metadata_description_gin_idx"',
        ),
    ]
