# Generated by Django 5.0.9 on 2024-11-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geant_argus", "0006_blacklists"),
        ("blacklist", "0002_copy_blacklists"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blacklist",
        ),
    ]
