# Generated by Django 5.2 on 2025-07-11 15:11

from django.db import migrations

ARGUS_APP = "argus_incident"


class Migration(migrations.Migration):
    """
    Create a partial index that only contains the rows that are not hidden.
    A normal index on the hidden field was not being utilized by the query planner
    """

    dependencies = [
        ("geant_argus", "0007_delete_blacklist"),
    ]

    operations = [
        migrations.RunSQL(
            sql=f"CREATE INDEX hidden_incident_index "
                f"ON {ARGUS_APP}_incident((metadata ->> 'hidden')) "
                "WHERE (metadata -> 'hidden') IS NULL OR (metadata -> 'hidden') = 'false'::jsonb",
            reverse_sql='DROP INDEX "hidden_incident_index"'
        )
    ]
