# Generated by Django 5.2 on 2025-08-11 12:33
# This converts all severities from old to new
# Includes incrementing the level and changing the names

from django.db import migrations

SEVERITY_CONVERSIONS_ARGUS = {
    "CRITICAL": "CRITICAL",
    "HIGH": "CRITICAL",
    "MEDIUM": "MAJOR",
    "LOW": "MINOR",
    "INFO": "WARNING",
    "MAJOR": "MAJOR",  # In case severities are already converted for some reason
    "MINOR": "MINOR",
    "WARNING": "WARNING",
    "HIDE": "HIDE",
}

SEVERITY_CONVERSIONS_DASHBOARD = {
    "CRITICAL_ISO270001": "CRITICAL",  # Not expected but just in case
    "CRITICAL": "HIGH",
    "MAJOR": "MEDIUM",
    "MINOR": "LOW",
    "WARNING": "INFO",
    "HIDE": "INFO",
    "HIGH": "HIGH",  # In case severities are already converted for some reason
    "MEDIUM": "MEDIUM",
    "LOW": "LOW",
    "INFO": "INFO",
}


def increment_level(apps, schema_editor):
    Incident = apps.get_model("argus_incident", "Incident")

    all_incidents = Incident.objects.all()
    for incident in all_incidents:
        incident.metadata['hidden'] = False
        new_sev = SEVERITY_CONVERSIONS_DASHBOARD[incident.metadata['severity']]
        incident.metadata['severity'] = new_sev
        incident.level = min(incident.level + 1, 5)
        if original_sev := incident.metadata['blacklist'].get('original_severity'):
            new_bl_sev = SEVERITY_CONVERSIONS_DASHBOARD[original_sev]
            incident.metadata['blacklist']['original_severity'] = new_bl_sev

    Incident.objects.bulk_update(all_incidents, ['level', 'metadata'], batch_size=1000)


def decrement_level(apps, schema_editor):
    Incident = apps.get_model("argus_incident", "Incident")

    all_incidents = Incident.objects.all()
    for incident in all_incidents:
        incident.metadata.pop('hidden')
        new_sev = SEVERITY_CONVERSIONS_ARGUS[incident.metadata['severity']]
        incident.metadata['severity'] = new_sev
        incident.level = max(incident.level - 1, 1)
        if original_sev := incident.metadata['blacklist'].get('original_severity'):
            new_bl_sev = SEVERITY_CONVERSIONS_ARGUS[original_sev]
            incident.metadata['blacklist']['original_severity'] = new_bl_sev
    Incident.objects.bulk_update(all_incidents, ['level', 'metadata'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("geant_argus", "0008_create_hidden_incident_index"),
    ]

    operations = [
        migrations.RunPython(increment_level, decrement_level),
    ]
