# Generated by Django 5.2 on 2025-08-11 12:33

from django.db import migrations
from django.db.models import Case, When, Value


def increment_level(apps, schema_editor):
    Incident = apps.get_model("argus_incident", "Incident")
    Incident.objects.all().update(level=Case(
        When(level=1, then=Value(2)),
        When(level=2, then=Value(3)),
        When(level=3, then=Value(4)),
        When(level=4, then=Value(5)),
        When(level=5, then=Value(5)),
    ))


def decrement_level(apps, schema_editor):
    Incident = apps.get_model("argus_incident", "Incident")
    Incident.objects.all().update(level=Case(
        When(level=5, then=Value(4)),
        When(level=4, then=Value(3)),
        When(level=3, then=Value(2)),
        When(level=2, then=Value(1)),
        When(level=1, then=Value(1)),
    ))


class Migration(migrations.Migration):

    dependencies = [
        ("geant_argus", "0008_create_hidden_incident_index"),
    ]

    operations = [
        migrations.RunPython(increment_level, decrement_level),
    ]
