# Generated by Django 5.2 on 2025-06-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blacklist", "0004_blacklist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="blacklist",
            name="hidden",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
