# Generated by Django 5.2 on 2025-08-21 15:49

from django.db import migrations
from django.db.models import Case, When, Value


def increment_level(apps, schema_editor):
    Blacklist = apps.get_model("blacklist", "Blacklist")
    Blacklist.objects.all().update(level=Case(
        When(level=1, then=Value(2)),
        When(level=2, then=Value(3)),
        When(level=3, then=Value(4)),
        When(level=4, then=Value(5)),
        When(level=5, then=Value(5)),
    ))


def decrement_level(apps, schema_editor):
    Blacklist = apps.get_model("blacklist", "Blacklist")
    Blacklist.objects.all().update(level=Case(
        When(level=5, then=Value(4)),
        When(level=4, then=Value(3)),
        When(level=3, then=Value(2)),
        When(level=2, then=Value(1)),
        When(level=1, then=Value(1)),
    ))


class Migration(migrations.Migration):

    dependencies = [
        ("blacklist", "0005_blacklist_hidden"),
    ]

    operations = [
        migrations.RunPython(increment_level, decrement_level),
    ]
